# Number of training epochs
epochs: 20

# Batch size
batch_size: 16

# Input image size
image_size: 640

# Number of dataloader workers
workers: 4


# Optimizer
optimizer: auto
learning_rate: 0.01
weight_decay: 0.0005


# Training Behaviour

# Early stopping patience
patience: 20
seed: 42
pretrained: true


# Data Augmentation
augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4

  degrees: 0.0
  translate: 0.1
  scale: 0.5

  fliplr: 0.5
  flipud: 0.0

  mosaic: 1.0
  mixup: 0.0

# Experiment Tracking
project_name: vehicle_damage_segmentation

experiment_name: baseline

output_dir: artifacts/training