# YOLO segmentation model checkpoint
model_name: yolo26n.pt

num_classes: 2

class_names:
  - dent
  - scratch

model_path: src/app/model/best_yolov8n.pt


# Confidence threshold
confidence_threshold: 0.405

# IoU threshold used during NMS
iou_threshold: 0.50

# Image size used during inference
image_size: 640

allowed_content_types:
  - image/jpeg
  - image/png
  - image/jpg
  - image/webp