# YOLO segmentation model checkpoint
model_name: yolo26m.pt

num_classes: 2

class_names:
  - dent
  - scratch

model_path: src/app/model/new_carrd.pt


# Image size used during inference
image_size: 640

allowed_content_types:
  - image/jpeg
  - image/png
  - image/jpg
  - image/webp